/** Map block titles to contextual icon names used by Icon.astro. */

const rules: Array<[RegExp, string]> = [
  [/chevron|dropdown/i, 'chevron-down'],
  [/underwrit|prefill/i, 'clipboard'],
  [/telematic/i, 'car'],
  [/computer vision|claims|damage/i, 'camera'],
  [/customer interaction|call|chat/i, 'phone'],
  [/model ops|agentops|operate|observ/i, 'activity'],
  [/accelerat/i, 'rocket'],
  [/insurance/i, 'shield'],
  [/financial|bank|credit|kyc|fraud/i, 'landmark'],
  [/human resources|onboarding/i, 'users'],
  [/supply chain|vendor/i, 'factory'],
  [/customer operations/i, 'phone'],
  [/manufactur|quality inspect/i, 'factory'],
  [/retail|cpg|merchand/i, 'shopping-bag'],
  [/media|telecom|technology/i, 'radio'],
  [/gdpr|privacy|ai act|nis2/i, 'scale'],
  [/soc|us privacy|encrypt/i, 'lock'],
  [/residenc|customer data control|vpc/i, 'key'],
  [/audit|incident|evidence/i, 'file-text'],
  [/nist/i, 'clipboard'],
  [/data processing|ingest|collect|source/i, 'download'],
  [/evaluat|quality|retrieval/i, 'clipboard'],
  [/process and contextual|chunk|pipeline/i, 'layers'],
  [/govern access|rbac/i, 'lock'],
  [/cloud you choose|multi-cloud|backend/i, 'cloud'],
  [/human|oversight|gate/i, 'users'],
  [/identity|sso/i, 'key'],
  [/redact|minimiz/i, 'eye'],
  [/trace|log/i, 'activity'],
  [/support|ticket/i, 'phone'],
  [/operations(?!ize)/i, 'settings'],
  [/finance & account|invoice/i, 'bar-chart'],
  [/research/i, 'search'],
  [/sales|marketing/i, 'sparkles'],
  [/industry vertical/i, 'globe'],
  [/build(?!ing)/i, 'hammer'],
  [/connect|integration/i, 'plug'],
  [/understand|knowledge|rag|document/i, 'database'],
  [/crm|service/i, 'users'],
  [/data & analytic|warehouse/i, 'bar-chart'],
  [/productivity|workspace/i, 'layout'],
  [/erp/i, 'briefcase'],
  [/developer|github/i, 'bot'],
  [/custom tool|mcp|openapi/i, 'webhook'],
  [/visual canvas|workflow/i, 'workflow'],
  [/version/i, 'git-branch'],
  [/test & eval/i, 'check'],
  [/toolkit/i, 'wrench'],
  [/blog/i, 'book'],
  [/doc/i, 'file-text'],
  [/rss/i, 'rss'],
  [/about/i, 'users'],
  [/career/i, 'briefcase'],
  [/get started/i, 'rocket'],
  [/contact/i, 'phone'],
  [/discover|inventor|map/i, 'map'],
  [/design|architect/i, 'pencil'],
  [/deploy|ship/i, 'rocket'],
  [/strategy|advisory|roadmap/i, 'map'],
  [/engineering|automat/i, 'bot'],
  [/compliance|security/i, 'shield'],
  [/gap|fail|silo|fragment|lock-in|paper/i, 'alert'],
  [/context layer|future/i, 'brain'],
  [/databricks|snowflake|saas/i, 'database'],
  [/prefill|worker/i, 'clipboard'],
  [/p&c|claims use/i, 'camera'],
  [/savings|39%/i, 'bar-chart'],
  [/customer stor/i, 'file-text'],
];

export function iconForTitle(title: string, fallback = 'layers'): string {
  for (const [pattern, icon] of rules) {
    if (pattern.test(title)) return icon;
  }
  return fallback;
}
